# Generated by Django 3.1.7 on 2021-02-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('am_employee_number', models.CharField(max_length=7)),
                ('am_key', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('passw', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('surname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('shipping_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Binding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binding_id', models.CharField(max_length=10)),
                ('binding_type', models.CharField(max_length=150)),
                ('binding_base_price', models.FloatField(default=0.0, max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='BindingSpecs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binding_specs_id', models.CharField(max_length=5)),
                ('q_item_id', models.CharField(max_length=10)),
                ('binding_id', models.CharField(max_length=10)),
                ('binding_specs_desc', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors_id', models.CharField(max_length=10)),
                ('colors_name', models.CharField(max_length=10)),
                ('colors_price_factor', models.FloatField(default=0.0, max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='ColorsSpecs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_specs_id', models.CharField(choices=[('bw', 'Black and White'), ('color', 'Colored')], max_length=15)),
                ('q_item_id', models.CharField(max_length=10)),
                ('colors_id', models.CharField(max_length=10)),
                ('colors_specs_desc', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_employee_number', models.CharField(max_length=7)),
                ('plate_number', models.CharField(blank=True, max_length=6, null=True)),
                ('license_number', models.CharField(blank=True, max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DieCut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diecut_id', models.CharField(max_length=10)),
                ('diecut_type', models.CharField(max_length=10)),
                ('diecut_base_price', models.FloatField(default=0.0, max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='DiecutSpecs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diecut_specs_id', models.CharField(max_length=5)),
                ('q_item_id', models.CharField(max_length=10)),
                ('diecut_id', models.CharField(max_length=10)),
                ('diecut_specs_desc', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=7)),
                ('employee_name', models.CharField(max_length=20)),
                ('job_position', models.CharField(choices=[('O', 'Owner'), ('AM', 'Assistant Manager'), ('D', 'Deliveryman'), ('P', 'Production Employee')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=10)),
                ('total_price', models.FloatField(default=0.0, max_length=22)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='paid', max_length=6)),
                ('invoice_email', models.CharField(max_length=20)),
                ('i_d_employee_number', models.CharField(max_length=7)),
                ('invoice_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_status', models.CharField(choices=[('inprogress', 'In-Progress'), ('finished', 'Finished')], max_length=11)),
                ('joborder_quotation_number', models.CharField(max_length=10)),
                ('joborder_number', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Lamination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lamination_id', models.CharField(max_length=10)),
                ('lamination_type', models.CharField(max_length=150)),
                ('lamination_base_price', models.FloatField(default=0.0, max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='LaminationSpecs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lamination_specs_id', models.CharField(choices=[('lam', 'Laminated'), ('notlam', 'Not Laminated')], max_length=13)),
                ('q_item_id', models.CharField(max_length=10)),
                ('lamination_id', models.CharField(max_length=10)),
                ('lamination_specs_desc', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_employee_number', models.CharField(max_length=7)),
                ('o_key', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.CharField(max_length=10)),
                ('paper_type', models.CharField(default='Book 60', max_length=150)),
                ('paper_category', models.CharField(max_length=15)),
                ('paper_height', models.CharField(max_length=10)),
                ('paper_width', models.CharField(max_length=10)),
                ('ream_cost', models.FloatField(blank=True, default=0.0, max_length=22, null=True)),
                ('leaf_cost', models.FloatField(blank=True, default=0.0, max_length=22, null=True)),
                ('is_colored', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1)),
                ('is_sticker', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PaperSpecs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_specs_id', models.CharField(max_length=5)),
                ('q_item_id', models.CharField(max_length=10)),
                ('paper_id', models.CharField(max_length=10)),
                ('paper_specs_desc', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_id', models.CharField(max_length=10)),
                ('no_impressions', models.IntegerField(default=1)),
                ('extra_impressions', models.IntegerField(default=0)),
                ('total_impressions', models.IntegerField(default=0)),
                ('running_costs', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='PrintingProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.CharField(max_length=10)),
                ('process_name', models.CharField(max_length=10)),
                ('process_base_factor', models.FloatField(default=0.0, max_length=22)),
            ],
        ),
        migrations.CreateModel(
            name='PrintingProcessSpecs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_specs_id', models.CharField(choices=[('offset', 'Offset'), ('digital', 'Digital'), ('screen', 'Screen')], max_length=7)),
                ('q_item_id', models.CharField(max_length=10)),
                ('process_id', models.CharField(max_length=10)),
                ('process_specs_desc', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(max_length=5)),
                ('product_name', models.CharField(max_length=20)),
                ('product_price', models.FloatField(default=0.0, max_length=22)),
                ('product_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_employee_number', models.CharField(max_length=7)),
                ('p_position', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionConstants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constants_id', models.CharField(max_length=10)),
                ('plate_base_price', models.FloatField(default=250.0)),
                ('base_price_fold', models.FloatField(default=90.0)),
                ('lamination_factor', models.FloatField(default=0.00625)),
                ('min_rate_running', models.FloatField(default=400.0)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_number', models.CharField(max_length=10)),
                ('approval_status', models.CharField(choices=[('notapproved', 'Not Approved'), ('inprogress', 'In Progress'), ('approved', 'Approved')], max_length=12)),
                ('product_specifications', models.CharField(max_length=200)),
                ('q_product_number', models.CharField(max_length=5)),
                ('q_am_employee_number', models.CharField(max_length=7)),
                ('q_email', models.CharField(max_length=20)),
                ('q_date', models.DateTimeField()),
                ('final_unit_costs', models.FloatField(default=0.0)),
                ('final_total_costs', models.FloatField(default=0.0)),
                ('raw_total_costs', models.FloatField(default=0.0)),
                ('margin_of_error', models.FloatField(default=0.1, max_length=10)),
                ('markup_percentage', models.FloatField(default=0.45, max_length=10)),
                ('pages_can_fit', models.CharField(max_length=4)),
                ('project_file_path', models.CharField(default='', max_length=255)),
                ('project_dimensions_length', models.FloatField(default=11)),
                ('project_dimensions_width', models.FloatField(default=8.5)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_item_id', models.CharField(max_length=10)),
                ('q_number', models.CharField(max_length=12)),
                ('color_specs_id', models.CharField(choices=[('bw', 'Black and White'), ('color', 'Colored')], max_length=15)),
                ('process_specs_id', models.CharField(choices=[('offset', 'Offset'), ('digital', 'Digital'), ('screen', 'Screen')], max_length=7)),
                ('lamination_specs_id', models.CharField(choices=[('lam', 'Laminated'), ('notlam', 'Not Laminated')], max_length=13)),
                ('diecut_specs_id', models.CharField(blank=True, max_length=5, null=True)),
                ('folded_size_specs_id', models.CharField(choices=[('a4', 'A4'), ('letter', 'Letter'), ('legal', 'Legal')], max_length=6)),
                ('spread_size_specs_id', models.CharField(choices=[('printer', 'Printer Spread'), ('doublespread', 'Double Spread')], max_length=15)),
                ('binding_specs_id', models.CharField(blank=True, max_length=5, null=True)),
                ('item_type', models.CharField(choices=[('inner', 'Inner Pages'), ('cover', 'Cover'), ('other', 'Other')], max_length=10)),
                ('item_type_other', models.CharField(max_length=10)),
            ],
        ),
    ]
