# Generated by Django 3.1.7 on 2021-03-02 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plate',
            name='quotation_item',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='quotation',
        ),
        migrations.AddField(
            model_name='quotation',
            name='quotation_items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='api.quotationitem'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='plates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_item', to='api.plate'),
        ),
    ]
