# Generated by Django 3.1.7 on 2021-03-04 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_quotation_total_no_plates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='total_plate_costs',
        ),
    ]
