# Generated by Django 3.1.7 on 2021-03-02 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210302_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='no_plates',
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='no_plates',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='approval_status',
            field=models.CharField(choices=[('not_approved', 'Not Approved'), ('in_progress', 'In Progress'), ('approved', 'Approved')], default='in_progress', max_length=12),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.product'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='q_am_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.accountmanager'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='binding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.binding'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='lamination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.lamination'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='plates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_item', to='api.plate'),
        ),
    ]
