# Generated by Django 3.1.7 on 2021-03-02 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='am_key',
            new_name='account_manager_key',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='o_key',
            new_name='owner_key',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='p_position',
            new_name='production_employee_position',
        ),
    ]
