# Generated by Django 3.1.7 on 2021-03-02 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210302_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='quotation_items',
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='quotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.quotation'),
        ),
    ]
