# Generated by Django 3.1.7 on 2021-03-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210302_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='job_position',
            field=models.CharField(blank=True, choices=[('O', 'Owner'), ('AM', 'Account Manager'), ('D', 'Deliveryman'), ('P', 'Production Employee')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='middle_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='production_employee_position',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
