# Generated by Django 3.1.7 on 2021-03-02 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210302_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='plates',
        ),
        migrations.AddField(
            model_name='plate',
            name='quotation_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plates', to='api.quotationitem'),
        ),
    ]
