# Generated by Django 3.1.7 on 2021-03-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210302_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionconstants',
            options={'verbose_name_plural': 'Production Constants'},
        ),
    ]
