# Generated by Django 3.1.7 on 2021-03-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210302_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='binding',
            options={'verbose_name_plural': 'Binding Types'},
        ),
        migrations.AlterModelOptions(
            name='diecut',
            options={'verbose_name_plural': 'Diecut Types'},
        ),
        migrations.AlterModelOptions(
            name='lamination',
            options={'verbose_name_plural': 'Lamination Types'},
        ),
        migrations.AlterModelOptions(
            name='printingprocess',
            options={'verbose_name_plural': 'Printing Processes'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Product Types'},
        ),
    ]
