# Generated by Django 3.1.7 on 2021-03-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210302_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'verbose_name_plural': 'Paper Types'},
        ),
        migrations.RenameField(
            model_name='account',
            old_name='production_employee_position',
            new_name='production_staff_position',
        ),
        migrations.AlterField(
            model_name='account',
            name='shipping_address',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
