# Generated by Django 3.1.7 on 2021-03-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210302_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='no_plates',
        ),
        migrations.AddField(
            model_name='quotation',
            name='total_no_plates',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quotation',
            name='total_running_costs',
            field=models.FloatField(default=0.0),
        ),
    ]
