# Generated by Django 3.1.7 on 2021-03-04 09:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210304_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='total_running_costs',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 9, 49, 48, 602061, tzinfo=utc)),
        ),
    ]
