# Generated by Django 3.1.7 on 2021-03-04 09:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210304_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='total_folding_costs',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 9, 59, 43, 97653, tzinfo=utc)),
        ),
    ]
