# Generated by Django 3.1.7 on 2021-03-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210303_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='quotation_running_costs',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
