# Generated by Django 3.1.7 on 2021-03-04 10:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210304_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='total_gathering_costs',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 10, 6, 22, 493983, tzinfo=utc)),
        ),
    ]
