# Generated by Django 3.1.7 on 2021-03-04 10:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210304_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 10, 38, 30, 808925, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='lamination_costs',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
