# Generated by Django 3.1.7 on 2021-03-07 04:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20210306_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='paper_height',
            field=models.FloatField(default=11.0),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper_width',
            field=models.FloatField(default=8.5),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 4, 31, 28, 923526, tzinfo=utc)),
        ),
    ]
