# Generated by Django 3.1.7 on 2021-03-07 15:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20210307_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='no_sheets_ordered',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='no_sheets_ordered',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 15, 56, 24, 108689, tzinfo=utc)),
        ),
    ]
