# Generated by Django 3.1.7 on 2021-03-07 16:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20210308_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lamination',
            old_name='lamination_base_price',
            new_name='base_price',
        ),
        migrations.AddField(
            model_name='lamination',
            name='min_rate',
            field=models.FloatField(blank=True, default=0.0, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 16, 31, 8, 658112, tzinfo=utc)),
        ),
    ]
