# Generated by Django 3.1.7 on 2021-03-10 06:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20210308_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='paper_height',
            new_name='paper_length',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 6, 34, 39, 579031, tzinfo=utc)),
        ),
    ]
