# Generated by Django 3.1.7 on 2021-04-26 02:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20210416_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='production_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('inprogress', 'In-Progress'), ('delivery', 'Out for Delivery'), ('finished', 'Finished')], max_length=11),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 2, 38, 50, 224250, tzinfo=utc)),
        ),
    ]
