# Generated by Django 3.2 on 2021-04-27 07:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20210426_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='created_date',
            field=models.DateTimeField(default=datetime.date(2021, 4, 27)),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 7, 50, 56, 967290, tzinfo=utc)),
        ),
    ]
