# Generated by Django 3.2 on 2021-04-28 21:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20210428_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 28, 21, 24, 1, 794039, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='approval_status',
            field=models.CharField(choices=[('computed', 'Computed'), ('not_approved', 'Not Approved'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('archived', 'Archived')], default='in_progress', max_length=12),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 28, 21, 24, 1, 791039, tzinfo=utc)),
        ),
    ]
