# Generated by Django 3.1.7 on 2021-03-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_quotation_total_plate_costs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='pages_can_fit',
            field=models.IntegerField(default=1),
        ),
    ]
