# Generated by Django 3.1.7 on 2021-03-04 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210304_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='total_paper_costs',
        ),
    ]
