# Generated by Django 3.1.7 on 2021-03-04 09:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_quotation_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 9, 44, 17, 565695, tzinfo=utc)),
        ),
    ]
