# Generated by Django 3.1.7 on 2021-03-04 10:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210304_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='raw_total_costs',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 10, 13, 13, 467101, tzinfo=utc)),
        ),
    ]
