# Generated by Django 3.1.7 on 2021-03-04 10:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210304_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='total_lamination_costs',
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='lamination_costs',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 10, 22, 49, 530929, tzinfo=utc)),
        ),
    ]
