# Generated by Django 3.1.7 on 2021-03-04 10:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210304_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 10, 36, 2, 648945, tzinfo=utc)),
        ),
    ]
