# Generated by Django 3.1.7 on 2021-03-04 10:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210304_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 10, 42, 51, 842779, tzinfo=utc)),
        ),
    ]
