# Generated by Django 3.1.7 on 2021-03-06 02:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210306_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='paper_height',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper_width',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 2, 10, 2, 647512, tzinfo=utc)),
        ),
    ]
