# Generated by Django 3.1.7 on 2021-03-07 05:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20210307_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='paper_height',
            field=models.FloatField(default=25.0),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper_width',
            field=models.FloatField(default=38.0),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 5, 10, 40, 526283, tzinfo=utc)),
        ),
    ]
