# Generated by Django 3.1.7 on 2021-03-07 07:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20210307_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binding',
            name='binding_base_price',
            field=models.FloatField(blank=True, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='binding',
            name='binding_type',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='diecut',
            name='diecut_base_price',
            field=models.FloatField(blank=True, default=0.0, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='diecut',
            name='diecut_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='lamination',
            name='lamination_base_price',
            field=models.FloatField(blank=True, default=0.0, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='lamination',
            name='lamination_type',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper_type',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.FloatField(blank=True, default=0.0, max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 7, 24, 42, 577918, tzinfo=utc)),
        ),
    ]
