# Generated by Django 3.1.7 on 2021-03-07 16:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20210307_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 16, 1, 17, 530467, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='no_sheets_ordered',
            field=models.FloatField(default=1),
        ),
    ]
