# Generated by Django 3.1.7 on 2021-03-07 16:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20210308_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotationitem',
            old_name='no_sheets_ordered',
            new_name='no_sheets_ordered_for_one',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 16, 7, 11, 750657, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='no_sheets_in_running_machine',
            field=models.FloatField(default=1.0),
        ),
    ]
