# Generated by Django 3.1.7 on 2021-03-07 16:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20210308_0007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotationitem',
            old_name='no_sheets_ordered_for_one',
            new_name='no_sheets_ordered_for_copy',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 16, 12, 51, 724809, tzinfo=utc)),
        ),
    ]
