# Generated by Django 3.1.7 on 2021-03-07 18:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20210308_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraPlate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_plate_name', models.CharField(default='Extra Plate', max_length=150)),
                ('no_impressions', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='no_impressions_per_plate',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='no_plates_per_copy',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 18, 26, 3, 484230, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Plate',
        ),
        migrations.AddField(
            model_name='extraplate',
            name='quotation_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_plates', to='api.quotationitem'),
        ),
    ]
