# Generated by Django 3.1.7 on 2021-03-07 18:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20210308_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='no_sheets_in_running_machine',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 7, 18, 51, 38, 566833, tzinfo=utc)),
        ),
    ]
