# Generated by Django 3.1.7 on 2021-03-08 10:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_auto_20210308_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 10, 54, 30, 560719, tzinfo=utc)),
        ),
    ]
