# Generated by Django 3.1.7 on 2021-03-10 06:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20210310_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='leaf_cost',
            new_name='sheet_cost',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 6, 47, 49, 468215, tzinfo=utc)),
        ),
    ]
