# Generated by Django 3.1.7 on 2021-04-15 22:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20210322_0129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joborder',
            old_name='joborder_number',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='joborder',
            name='joborder_quotation_number',
        ),
        migrations.AddField(
            model_name='joborder',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.account'),
        ),
        migrations.AddField(
            model_name='joborder',
            name='quotation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.quotation'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 22, 41, 55, 18965, tzinfo=utc)),
        ),
    ]
