# Generated by Django 3.2 on 2021-04-27 07:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20210427_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 7, 53, 36, 750981, tzinfo=utc)),
        ),
    ]
