# Generated by Django 3.2 on 2021-04-28 08:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20210428_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joborder',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 28, 8, 58, 14, 898841, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.account'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 28, 8, 58, 14, 894798, tzinfo=utc)),
        ),
    ]
