export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const PROFILE_FOUND = "PROFILE_FOUND";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const CREATE_QUOTATION_SUCCESS = "CREATE_QUOTATION_SUCCESS";
export const CREATE_QUOTATION_FAIL = "CREATE_QUOTATION_FAIL";
export const RETRIEVE_QUOTATION_SUCCESS = "RETRIEVE_QUOTATION_SUCCESS";
export const RETRIEVE_QUOTATION_FAIL = "RETRIEVE_QUOTATION_FAIL";
export const UPDATE_QUOTATION_SUCCESS = "UPDATE_QUOTATION_SUCCESS";
export const UPDATE_QUOTATION_FAIL = "UPDATE_QUOTATION_FAIL";
export const DELETE_QUOTATION_SUCCESS = "DELETE_QUOTATION_SUCCESS";
export const DELETE_QUOTATION_FAIL = "DELETE_QUOTATION_FAIL";

export const RETRIEVE_ALL_QUOTATIONS_SUCCESS = "RETRIEVE_ALL_QUOTATIONS_SUCCESS";
export const RETRIEVE_ALL_QUOTATIONS_FAIL = "RETRIEVE_ALL_QUOTATIONS_FAIL";

export const RETRIEVE_COMPUTED_QUOTATIONS_SUCCESS = "RETRIEVE_COMPUTED_QUOTATIONS_SUCCESS";
export const RETRIEVE_COMPUTED_QUOTATIONS_FAIL = "RETRIEVE_COMPUTED_QUOTATIONS_FAIL";

export const RETRIEVE_IN_PROGRESS_QUOTATIONS_SUCCESS = "RETRIEVE_IN_PROGRESS_QUOTATIONS_SUCCESS";
export const RETRIEVE_IN_PROGRESS_QUOTATIONS_FAIL = "RETRIEVE_IN_PROGRESS_QUOTATIONS_FAIL";

export const RETRIEVE_APPROVED_QUOTATIONS_SUCCESS = "RETRIEVE_APPROVED_QUOTATIONS_SUCCESS";
export const RETRIEVE_APPROVED_QUOTATIONS_FAIL = "RETRIEVE_APPROVED_QUOTATIONS_FAIL";