export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

// USER PROFILES
export const PROFILE_FOUND = "PROFILE_FOUND";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const PROFILE_UPDATE_SUCCESS = "PROFILE_UPDATE_SUCCESS";
export const PROFILE_UPDATE_FAIL = "PROFILE_UPDATE_FAIL";
export const ALL_ACCOUNTS_FOUND = "ALL_ACCOUNTS_FOUND";
export const ALL_ACCOUNTS_NOT_FOUND = "ALL_ACCOUNTS_NOT_FOUND";

// CLIENT ACCOUNTS
export const CLIENTS_FOUND = "CLIENTS_FOUND";
export const CLIENTS_NOT_FOUND = "CLIENTS_NOT_FOUND";

// EMPLOYEE ACCOUNTS
export const PRODUCTION_EMPLOYEES_FOUND = "PRODUCTION_EMPLOYEES_FOUND";
export const PRODUCTION_EMPLOYEES_NOT_FOUND = "PRODUCTION_EMPLOYEES_NOT_FOUND";
export const DRIVER_EMPLOYEES_FOUND = "DELIVERYMAN_EMPLOYEES_FOUND";
export const DRIVER_EMPLOYEES_NOT_FOUND = "DELIVERYMAN_EMPLOYEES_NOT_FOUND";
export const ACCOUNT_MANAGER_EMPLOYEES_FOUND = "ACCOUNT_MANAGER_EMPLOYEES_FOUND";
export const ACCOUNT_MANAGER_EMPLOYEES_NOT_FOUND = "ACCOUNT_MANAGER_EMPLOYEES_NOT_FOUND";
export const OWNER_EMPLOYEES_FOUND = "OWNER_EMPLOYEES_FOUND";
export const OWNER_EMPLOYEES_NOT_FOUND = "OWNER_EMPLOYEES_NOT_FOUND";

// TODO: Remove unnecessary action types
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

// QUOTATIONS
export const CREATE_QUOTATION_SUCCESS = "CREATE_QUOTATION_SUCCESS";
export const CREATE_QUOTATION_FAIL = "CREATE_QUOTATION_FAIL";
export const RETRIEVE_QUOTATION_SUCCESS = "RETRIEVE_QUOTATION_SUCCESS";
export const RETRIEVE_QUOTATION_FAIL = "RETRIEVE_QUOTATION_FAIL";
export const UPDATE_QUOTATION_SUCCESS = "UPDATE_QUOTATION_SUCCESS";
export const UPDATE_QUOTATION_FAIL = "UPDATE_QUOTATION_FAIL";
export const DELETE_QUOTATION_SUCCESS = "DELETE_QUOTATION_SUCCESS";
export const DELETE_QUOTATION_FAIL = "DELETE_QUOTATION_FAIL";

export const RETRIEVE_ALL_QUOTATIONS_SUCCESS = "RETRIEVE_ALL_QUOTATIONS_SUCCESS";
export const RETRIEVE_ALL_QUOTATIONS_FAIL = "RETRIEVE_ALL_QUOTATIONS_FAIL";

export const RETRIEVE_COMPUTED_QUOTATIONS_SUCCESS = "RETRIEVE_COMPUTED_QUOTATIONS_SUCCESS";
export const RETRIEVE_COMPUTED_QUOTATIONS_FAIL = "RETRIEVE_COMPUTED_QUOTATIONS_FAIL";

export const RETRIEVE_IN_PROGRESS_QUOTATIONS_SUCCESS = "RETRIEVE_IN_PROGRESS_QUOTATIONS_SUCCESS";
export const RETRIEVE_IN_PROGRESS_QUOTATIONS_FAIL = "RETRIEVE_IN_PROGRESS_QUOTATIONS_FAIL";

export const RETRIEVE_APPROVED_QUOTATIONS_SUCCESS = "RETRIEVE_APPROVED_QUOTATIONS_SUCCESS";
export const RETRIEVE_APPROVED_QUOTATIONS_FAIL = "RETRIEVE_APPROVED_QUOTATIONS_FAIL";

// JOB ORDERS
export const CREATE_JOB_ORDER_SUCCESS="CREATE_JOB_ORDER_SUCCESS"
export const CREATE_JOB_ORDER_FAIL="CREATE_JOB_ORDER_FAIL"

export const RETRIEVE_PENDING_JOB_ORDERS_SUCCESS="RETRIEVE_PENDING_JOB_ORDERS_SUCCESS"
export const RETRIEVE_PENDING_JOB_ORDERS_FAIL="RETRIEVE_PENDING_JOB_ORDERS_FAIL"

export const RETRIEVE_IN_PROGRESS_JOB_ORDERS_SUCCESS="RETRIEVE_IN_PROGRESS_JOB_ORDERS_SUCCESS"
export const RETRIEVE_IN_PROGRESS_JOB_ORDERS_FAIL="RETRIEVE_IN_PROGRESS_JOB_ORDERS_FAIL"

export const RETRIEVE_OUT_FOR_DELIVERY_JOB_ORDERS_SUCCESS= "RETRIEVE_OUT_FOR_DELIVERY_JOB_ORDERS_SUCCESS"
export const RETRIEVE_OUT_FOR_DELIVERY_JOB_ORDERS_FAIL= "RETRIEVE_OUT_FOR_DELIVERY_JOB_ORDERS_FAIL"

export const RETRIEVE_FINISHED_JOB_ORDERS_SUCCESS= "RETRIEVE_FINISHED_JOB_ORDERS_SUCCESS"
export const RETRIEVE_FINISHED_JOB_ORDERS_FAIL= "RETRIEVE_FINISHED_JOB_ORDERS_FAIL"

export const START_JOB_ORDER_SUCCESS="START_JOB_ORDER_SUCCESS"
export const START_JOB_ORDER_FAIL="START_JOB_ORDER_FAIL"

export const DELIVER_JOB_ORDER_SUCCESS="DELIVER_JOB_ORDER_SUCCESS"
export const DELIVER_JOB_ORDER_FAIL="DELIVER_JOB_ORDER_FAIL"

export const FINISH_JOB_ORDER_SUCCESS="FINISH_JOB_ORDER_SUCCESS"
export const FINISH_JOB_ORDER_FAIL="FINISH_JOB_ORDER_FAIL"