import { v4 as uuid } from 'uuid';

export default [
  {
    id: uuid(),
    totalPrice: 'P3000.00',
    orderID: '#29JKFSPSE',
    orderPrice: 'P3000.00',
    unitCost: 'P1000.00',
    status: 'IN PRODUCTION',
    customerName: 'Juan Aquino',
    customerAddress: '1345 Quartz Street, Loyola Grand Villas, Loyola Heights, Quezon City',
    type: 'Book',
    quantity: '500',
    totalPages: '250',
    length: '8.5',
    width: '11',
    numberColors: '4 colors (CMYK)',

  },
  {
    id: uuid(),
    totalPrice: 'P3000.00',
    orderID: '#29JKFSPSE',
    orderPrice: 'P3000.00',
    unitCost: 'P1000.00',
    status: 'IN PRODUCTION',
    customerName: 'Juan Aquino',
    customerAddress: '1345 Quartz Street, Loyola Grand Villas, Loyola Heights, Quezon City',
    type: 'Book',
    quantity: '500',
    totalPages: '250',
    length: '8.5',
    width: '11',
    numberColors: '4 colors (CMYK)',
  },
  {
    id: uuid(),
    totalPrice: 'P3000.00',
    orderID: '#29JKFSPSE',
    orderPrice: 'P3000.00',
    unitCost: 'P1000.00',
    status: 'IN PRODUCTION',
    customerName: 'Juan Aquino',
    customerAddress: '1345 Quartz Street, Loyola Grand Villas, Loyola Heights, Quezon City',
    type: 'Book',
    quantity: '500',
    totalPages: '250',
    length: '8.5',
    width: '11',
    numberColors: '4 colors (CMYK)',
  },
];
